// ReAccess Dev. Studios - FreeDev Team
// SA-MP Serverside Include
// Name: IndexDrawer
// Version: 0.0a R0 BETA
// Author: [MMM] Anna SB
// Description: Simple Index-Based Text-To-Go Selection Menus. Simply With TextDraws, Fully Customizable.

#include <a_samp>

public OnPlayerConnect(playerid)
{
	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	return 1;
}

public OnPlayerText(playerid, text[])
{
	return 1;
}

public OnPlayerSelectedMenuRow(playerid, row)
{
	return 1;
}

public OnPlayerExitedMenu(playerid)
{
	return 1;
}

public OnPlayerKeyStateChange(playerid, newkeys, oldkeys)
{
	return 1;
}

public OnPlayerUpdate(playerid)
{
	return 1;
}

public OnDialogResponse(playerid, dialogid, response, listitem, inputtext[])
{
	return 1;
}
